# vim: set ft=yaml:
#
#

# port
# the ssh port listen on
port: 2022

# obfs_key
#
# Specifies the key to encrypt the connection,
# if obfs enabled, only client known this key
# can connect
obfs_key: some_keyword

# ssh host key file
host_key_file: ./ssh_host_rsa_key

# obfs_method
#
# Specifies the encryption method.
# when this option is specified, the entire connection 
# will be encrypted.
# when set to none, the encryption is disabled.
# Avaliable methods: rc4, aes, none(default)
#
obfs_method: "rc4"

# when set to true, only the ssh handshake packet is encrypted
disable_obfs_after_handshake: true

# show more log message
# value true or false
debug: true

# the users used by ssh server
# user can authorite by passwrod or by public key
# public key as same as OpenSSH
# public key or password must be specify one
#
users:
    - 
      # username
      username: user1
      # password, empty password means disable password authorize
      password: ""
      # public key file
      authorized_key_file: /path/to/user/authorized_keys
    - 
      username: user2
      password: user2
      authorized_key_file: /path/to/user/authorized_keys
    - 
      username: user3
      password: ""
      authorized_key_file: /path/to/authorized_keys


