# vim: set ft=yaml:
#
#

# port
# the ssh port listen on
listen:
    -  
      port: 2022
      key:
      cert:
    - 
      # this listen for TLS
      port: 2023
      key: server.key
      cert: server.crt

# ssh host key file
host_key_file: ./ssh_host_rsa_key

# show more log message
# value true or false
debug: true

# the users used by ssh server
# user can authorite by passwrod or by public key
# public key as same as OpenSSH
# public key or password must be specify one
#
users:
    - 
      # username
      username: user1
      # password, empty password means disable password authorize
      password: ""
      # public key file
      authorized_key_file: /path/to/user/authorized_keys
    - 
      username: user2
      password: user2
      authorized_key_file: /path/to/user/authorized_keys
    - 
      username: user3
      password: ""
      authorized_key_file: /path/to/authorized_keys


